namespace: mysql

replicas: 1
image:
  repo: mysql
  tag: "8.0"
port: 3306

secrets:
  MYSQL_ROOT_PASSWORD: placeholder_root_password
  MYSQL_USER: placeholder_mysql_user
  MYSQL_PASSWORD: placeholder_mysql_password

resources:
  requests:
    cpu: 200m
    memory: 1Gi
    storage: 1Gi
  limits:
    cpu: 200m
    memory: 1Gi