name: Deploy Helm
run-name: Deploy Helm Chart to ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        type: string
      version:
        description: 'Helm chart version'
        required: true
        type: string
      helm-values-path:
        description: 'Path to Helm values file'
        required: false
        type: string
        default: './helm-charts/todoapp/values.yaml'
      cluster-config-path:
        description: 'Path to kind cluster config file'
        required: false
        type: string
        default: 'cluster.yml'

env:
  HELM_RELEASE_NAME: todoapp
  KIND_CLUSTER_NAME: todoapp-cluster
  CHART_PKG_PATH: ./helm-charts/packages
  DOCKER_IMAGE_NAME: todoapp

jobs:
  deploy-helm:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Packaged Helm Charts
        uses: actions/download-artifact@v4
        with:
          name: helm-packaged-artifacts
          path: ${{ env.CHART_PKG_PATH }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          config: ${{ inputs.cluster-config-path }}
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}

      - name: Dry-run Helm install
        run: |
          helm install --dry-run ${{ env.HELM_RELEASE_NAME }} \
            ${{ env.CHART_PKG_PATH }}/${{ env.DOCKER_IMAGE_NAME }}-${{ inputs.version }}.tgz

      - name: Deploy Helm Chart
        env:
          DOCKER_IMAGE_REPO: "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}"
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} \
            ${{ env.CHART_PKG_PATH }}/${{ env.DOCKER_IMAGE_NAME }}-${{ inputs.version }}.tgz \
            --namespace ${{ inputs.environment }} \
            --create-namespace \
            --atomic \
            --wait \
            --timeout 300s \
            -f ${{ inputs.helm-values-path }} \
            --set secretKey="${{ secrets.SECRET_KEY }}" \
            --set db.password="${{ secrets.DB_PASSWORD }}" \
            --set db.user="${{ secrets.DB_USER }}" \
            --set db.name="${{ secrets.DB_NAME }}" \
            --set db.host="${{ secrets.DB_HOST }}" \
            --set mysql.mysqlRootPassword="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --set mysql.mysqlPassword="${{ secrets.MYSQL_PASSWORD }}" \
            --set image.repository="${{ env.DOCKER_IMAGE_REPO }}" \
            --set image.tag="${{ inputs.version }}"