name: python-deployment

run-name: ${{ github.actor }} - ${{ github.ref_name}} -${{ github.sha }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9
  DOCKER_IMAGE_NAME: todoapp


jobs:
  python-ci:
    name: Python CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            src/requirements.txt
            src/requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Tests with Coverage
        run: |
          coverage run --source='.' manage.py test
          coverage report

      - name: Linting
        run: |
          flake8 . --show-source --statistics --exit-zero

      - name: Check Complexity
        run: |
          flake8 . --exit-zero --max-complexity=10

      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts
          path: src/*

      - name: Upload Helm Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-artifacts
          path: ${{ github.workspace }}/helm-charts/*

  docker-ci:
    name: Docker CI
    runs-on: ubuntu-latest
    needs: python-ci

    steps:
      - name: Download python artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-artifacts
          path: ./app

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

  helm-ci:
    name: Helm CI
    runs-on: ubuntu-latest
    needs: python-ci

    steps:
      - name: Download Helm Artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: ./helm-charts

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Lint Helm Charts
        run: helm lint helm-charts/todoapp

      - name: Template Helm Charts
        run: helm template todoapp helm-charts/todoapp -f helm-charts/todoapp/values.yaml

      - name: Package Helm Charts
        run: helm package helm-charts/todoapp --destination helm-charts/packages

      - name: Upload Packaged Helm Charts
        uses: actions/upload-artifact@v4
        with:
          name: helm-packaged-artifacts
          path: helm-charts/packages/*.tgz

  deploy-helm-dev:
    name: Deploy Helm to Dev
    needs: [helm-ci, docker-ci]
    uses: ./.github/workflows/helm-deployment.yml
    secrets: inherit
    with:
      environment: development
      version: '${{ github.sha }}'
      helm-values-path: './helm-charts/todoapp/values.yaml'

  deploy-helm-stg:
    name: Deploy Helm to Staging
    needs: [helm-ci, docker-ci]
    uses: ./.github/workflows/helm-deployment.yml
    secrets: inherit
    with:
      environment: staging
      version: '${{ github.sha }}'
      helm-values-path: './helm-charts/todoapp/values/stg.yaml'
